/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: ../hcpopenshiftclusters.go
//
// Generated by this command:
//
//	mockgen -destination hcpopenshiftclusters_mock.go -package mock_hcpopenshiftclusters -source ../hcpopenshiftclusters.go HcpOpenShiftClusterScope
//

// Package mock_hcpopenshiftclusters is a generated GoMock package.
package mock_hcpopenshiftclusters

import (
	context "context"
	reflect "reflect"
	time "time"

	azcore "github.com/Azure/azure-sdk-for-go/sdk/azcore"
	gomock "go.uber.org/mock/gomock"
	v1beta1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
	azure "sigs.k8s.io/cluster-api-provider-azure/azure"
	generated "sigs.k8s.io/cluster-api-provider-azure/exp/third_party/aro-hcp/api/v20240610preview/generated"
	v1beta10 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// MockHcpOpenShiftClusterScope is a mock of HcpOpenShiftClusterScope interface.
type MockHcpOpenShiftClusterScope struct {
	ctrl     *gomock.Controller
	recorder *MockHcpOpenShiftClusterScopeMockRecorder
	isgomock struct{}
}

// MockHcpOpenShiftClusterScopeMockRecorder is the mock recorder for MockHcpOpenShiftClusterScope.
type MockHcpOpenShiftClusterScopeMockRecorder struct {
	mock *MockHcpOpenShiftClusterScope
}

// NewMockHcpOpenShiftClusterScope creates a new mock instance.
func NewMockHcpOpenShiftClusterScope(ctrl *gomock.Controller) *MockHcpOpenShiftClusterScope {
	mock := &MockHcpOpenShiftClusterScope{ctrl: ctrl}
	mock.recorder = &MockHcpOpenShiftClusterScopeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHcpOpenShiftClusterScope) EXPECT() *MockHcpOpenShiftClusterScopeMockRecorder {
	return m.recorder
}

// BaseURI mocks base method.
func (m *MockHcpOpenShiftClusterScope) BaseURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURI indicates an expected call of BaseURI.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) BaseURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURI", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).BaseURI))
}

// ClientID mocks base method.
func (m *MockHcpOpenShiftClusterScope) ClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientID indicates an expected call of ClientID.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) ClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientID", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).ClientID))
}

// ClientSecret mocks base method.
func (m *MockHcpOpenShiftClusterScope) ClientSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientSecret indicates an expected call of ClientSecret.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) ClientSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientSecret", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).ClientSecret))
}

// CloudEnvironment mocks base method.
func (m *MockHcpOpenShiftClusterScope) CloudEnvironment() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudEnvironment")
	ret0, _ := ret[0].(string)
	return ret0
}

// CloudEnvironment indicates an expected call of CloudEnvironment.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) CloudEnvironment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudEnvironment", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).CloudEnvironment))
}

// DefaultedAzureCallTimeout mocks base method.
func (m *MockHcpOpenShiftClusterScope) DefaultedAzureCallTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultedAzureCallTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultedAzureCallTimeout indicates an expected call of DefaultedAzureCallTimeout.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) DefaultedAzureCallTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultedAzureCallTimeout", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).DefaultedAzureCallTimeout))
}

// DefaultedAzureServiceReconcileTimeout mocks base method.
func (m *MockHcpOpenShiftClusterScope) DefaultedAzureServiceReconcileTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultedAzureServiceReconcileTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultedAzureServiceReconcileTimeout indicates an expected call of DefaultedAzureServiceReconcileTimeout.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) DefaultedAzureServiceReconcileTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultedAzureServiceReconcileTimeout", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).DefaultedAzureServiceReconcileTimeout))
}

// DefaultedReconcilerRequeue mocks base method.
func (m *MockHcpOpenShiftClusterScope) DefaultedReconcilerRequeue() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultedReconcilerRequeue")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultedReconcilerRequeue indicates an expected call of DefaultedReconcilerRequeue.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) DefaultedReconcilerRequeue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultedReconcilerRequeue", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).DefaultedReconcilerRequeue))
}

// DeleteLongRunningOperationState mocks base method.
func (m *MockHcpOpenShiftClusterScope) DeleteLongRunningOperationState(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteLongRunningOperationState", arg0, arg1, arg2)
}

// DeleteLongRunningOperationState indicates an expected call of DeleteLongRunningOperationState.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) DeleteLongRunningOperationState(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLongRunningOperationState", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).DeleteLongRunningOperationState), arg0, arg1, arg2)
}

// GetLongRunningOperationState mocks base method.
func (m *MockHcpOpenShiftClusterScope) GetLongRunningOperationState(arg0, arg1, arg2 string) *v1beta1.Future {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLongRunningOperationState", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1beta1.Future)
	return ret0
}

// GetLongRunningOperationState indicates an expected call of GetLongRunningOperationState.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) GetLongRunningOperationState(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLongRunningOperationState", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).GetLongRunningOperationState), arg0, arg1, arg2)
}

// HashKey mocks base method.
func (m *MockHcpOpenShiftClusterScope) HashKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// HashKey indicates an expected call of HashKey.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) HashKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashKey", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).HashKey))
}

// HcpOpenShiftClusterSpecs mocks base method.
func (m *MockHcpOpenShiftClusterScope) HcpOpenShiftClusterSpecs(arg0 context.Context) azure.ResourceSpecGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HcpOpenShiftClusterSpecs", arg0)
	ret0, _ := ret[0].(azure.ResourceSpecGetter)
	return ret0
}

// HcpOpenShiftClusterSpecs indicates an expected call of HcpOpenShiftClusterSpecs.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) HcpOpenShiftClusterSpecs(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HcpOpenShiftClusterSpecs", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).HcpOpenShiftClusterSpecs), arg0)
}

// SetAPIURL mocks base method.
func (m *MockHcpOpenShiftClusterScope) SetAPIURL(url *string, visibility *generated.Visibility) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAPIURL", url, visibility)
}

// SetAPIURL indicates an expected call of SetAPIURL.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) SetAPIURL(url, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAPIURL", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).SetAPIURL), url, visibility)
}

// SetLongRunningOperationState mocks base method.
func (m *MockHcpOpenShiftClusterScope) SetLongRunningOperationState(arg0 *v1beta1.Future) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLongRunningOperationState", arg0)
}

// SetLongRunningOperationState indicates an expected call of SetLongRunningOperationState.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) SetLongRunningOperationState(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLongRunningOperationState", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).SetLongRunningOperationState), arg0)
}

// SetProvisioningState mocks base method.
func (m *MockHcpOpenShiftClusterScope) SetProvisioningState(state *generated.ProvisioningState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProvisioningState", state)
}

// SetProvisioningState indicates an expected call of SetProvisioningState.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) SetProvisioningState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvisioningState", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).SetProvisioningState), state)
}

// SetStatusVersion mocks base method.
func (m *MockHcpOpenShiftClusterScope) SetStatusVersion(version *generated.VersionProfile) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatusVersion", version)
}

// SetStatusVersion indicates an expected call of SetStatusVersion.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) SetStatusVersion(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusVersion", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).SetStatusVersion), version)
}

// SubscriptionID mocks base method.
func (m *MockHcpOpenShiftClusterScope) SubscriptionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriptionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SubscriptionID indicates an expected call of SubscriptionID.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) SubscriptionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriptionID", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).SubscriptionID))
}

// TenantID mocks base method.
func (m *MockHcpOpenShiftClusterScope) TenantID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantID")
	ret0, _ := ret[0].(string)
	return ret0
}

// TenantID indicates an expected call of TenantID.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) TenantID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantID", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).TenantID))
}

// Token mocks base method.
func (m *MockHcpOpenShiftClusterScope) Token() azcore.TokenCredential {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(azcore.TokenCredential)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).Token))
}

// UpdateDeleteStatus mocks base method.
func (m *MockHcpOpenShiftClusterScope) UpdateDeleteStatus(arg0 v1beta10.ConditionType, arg1 string, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDeleteStatus", arg0, arg1, arg2)
}

// UpdateDeleteStatus indicates an expected call of UpdateDeleteStatus.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) UpdateDeleteStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeleteStatus", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).UpdateDeleteStatus), arg0, arg1, arg2)
}

// UpdatePatchStatus mocks base method.
func (m *MockHcpOpenShiftClusterScope) UpdatePatchStatus(arg0 v1beta10.ConditionType, arg1 string, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePatchStatus", arg0, arg1, arg2)
}

// UpdatePatchStatus indicates an expected call of UpdatePatchStatus.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) UpdatePatchStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePatchStatus", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).UpdatePatchStatus), arg0, arg1, arg2)
}

// UpdatePutStatus mocks base method.
func (m *MockHcpOpenShiftClusterScope) UpdatePutStatus(arg0 v1beta10.ConditionType, arg1 string, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePutStatus", arg0, arg1, arg2)
}

// UpdatePutStatus indicates an expected call of UpdatePutStatus.
func (mr *MockHcpOpenShiftClusterScopeMockRecorder) UpdatePutStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePutStatus", reflect.TypeOf((*MockHcpOpenShiftClusterScope)(nil).UpdatePutStatus), arg0, arg1, arg2)
}
