/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: ../hcpopenshiftclustercredentials.go
//
// Generated by this command:
//
//	mockgen -destination hcpopenshiftclustercredentials_mock.go -package mock_hcpopenshiftclustercredentials -source ../hcpopenshiftclustercredentials.go HcpOpenShiftClusterCredentialScope
//

// Package mock_hcpopenshiftclustercredentials is a generated GoMock package.
package mock_hcpopenshiftclustercredentials

import (
	context "context"
	reflect "reflect"
	time "time"

	azcore "github.com/Azure/azure-sdk-for-go/sdk/azcore"
	gomock "go.uber.org/mock/gomock"
	v1beta1 "sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
	azure "sigs.k8s.io/cluster-api-provider-azure/azure"
	v1beta10 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// MockHcpOpenShiftClusterCredentialScope is a mock of HcpOpenShiftClusterCredentialScope interface.
type MockHcpOpenShiftClusterCredentialScope struct {
	ctrl     *gomock.Controller
	recorder *MockHcpOpenShiftClusterCredentialScopeMockRecorder
	isgomock struct{}
}

// MockHcpOpenShiftClusterCredentialScopeMockRecorder is the mock recorder for MockHcpOpenShiftClusterCredentialScope.
type MockHcpOpenShiftClusterCredentialScopeMockRecorder struct {
	mock *MockHcpOpenShiftClusterCredentialScope
}

// NewMockHcpOpenShiftClusterCredentialScope creates a new mock instance.
func NewMockHcpOpenShiftClusterCredentialScope(ctrl *gomock.Controller) *MockHcpOpenShiftClusterCredentialScope {
	mock := &MockHcpOpenShiftClusterCredentialScope{ctrl: ctrl}
	mock.recorder = &MockHcpOpenShiftClusterCredentialScopeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHcpOpenShiftClusterCredentialScope) EXPECT() *MockHcpOpenShiftClusterCredentialScopeMockRecorder {
	return m.recorder
}

// AnnotateKubeconfigInvalid mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) AnnotateKubeconfigInvalid(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnnotateKubeconfigInvalid", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnnotateKubeconfigInvalid indicates an expected call of AnnotateKubeconfigInvalid.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) AnnotateKubeconfigInvalid(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnnotateKubeconfigInvalid", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).AnnotateKubeconfigInvalid), ctx)
}

// BaseURI mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) BaseURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURI indicates an expected call of BaseURI.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) BaseURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURI", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).BaseURI))
}

// ClientID mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) ClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientID indicates an expected call of ClientID.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) ClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientID", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).ClientID))
}

// ClientSecret mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) ClientSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientSecret indicates an expected call of ClientSecret.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) ClientSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientSecret", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).ClientSecret))
}

// CloudEnvironment mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) CloudEnvironment() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudEnvironment")
	ret0, _ := ret[0].(string)
	return ret0
}

// CloudEnvironment indicates an expected call of CloudEnvironment.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) CloudEnvironment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudEnvironment", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).CloudEnvironment))
}

// DefaultedAzureCallTimeout mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) DefaultedAzureCallTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultedAzureCallTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultedAzureCallTimeout indicates an expected call of DefaultedAzureCallTimeout.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) DefaultedAzureCallTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultedAzureCallTimeout", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).DefaultedAzureCallTimeout))
}

// DefaultedAzureServiceReconcileTimeout mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) DefaultedAzureServiceReconcileTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultedAzureServiceReconcileTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultedAzureServiceReconcileTimeout indicates an expected call of DefaultedAzureServiceReconcileTimeout.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) DefaultedAzureServiceReconcileTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultedAzureServiceReconcileTimeout", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).DefaultedAzureServiceReconcileTimeout))
}

// DefaultedReconcilerRequeue mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) DefaultedReconcilerRequeue() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultedReconcilerRequeue")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// DefaultedReconcilerRequeue indicates an expected call of DefaultedReconcilerRequeue.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) DefaultedReconcilerRequeue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultedReconcilerRequeue", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).DefaultedReconcilerRequeue))
}

// DeleteLongRunningOperationState mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) DeleteLongRunningOperationState(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteLongRunningOperationState", arg0, arg1, arg2)
}

// DeleteLongRunningOperationState indicates an expected call of DeleteLongRunningOperationState.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) DeleteLongRunningOperationState(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLongRunningOperationState", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).DeleteLongRunningOperationState), arg0, arg1, arg2)
}

// GetLongRunningOperationState mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) GetLongRunningOperationState(arg0, arg1, arg2 string) *v1beta1.Future {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLongRunningOperationState", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1beta1.Future)
	return ret0
}

// GetLongRunningOperationState indicates an expected call of GetLongRunningOperationState.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) GetLongRunningOperationState(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLongRunningOperationState", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).GetLongRunningOperationState), arg0, arg1, arg2)
}

// HashKey mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) HashKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// HashKey indicates an expected call of HashKey.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) HashKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashKey", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).HashKey))
}

// HcpOpenShiftClusterCredentialsSpecs mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) HcpOpenShiftClusterCredentialsSpecs(arg0 context.Context) azure.ResourceSpecGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HcpOpenShiftClusterCredentialsSpecs", arg0)
	ret0, _ := ret[0].(azure.ResourceSpecGetter)
	return ret0
}

// HcpOpenShiftClusterCredentialsSpecs indicates an expected call of HcpOpenShiftClusterCredentialsSpecs.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) HcpOpenShiftClusterCredentialsSpecs(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HcpOpenShiftClusterCredentialsSpecs", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).HcpOpenShiftClusterCredentialsSpecs), arg0)
}

// SetKubeconfig mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) SetKubeconfig(kubeconfig *string, timestamp *time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKubeconfig", kubeconfig, timestamp)
}

// SetKubeconfig indicates an expected call of SetKubeconfig.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) SetKubeconfig(kubeconfig, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKubeconfig", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).SetKubeconfig), kubeconfig, timestamp)
}

// SetLongRunningOperationState mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) SetLongRunningOperationState(arg0 *v1beta1.Future) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLongRunningOperationState", arg0)
}

// SetLongRunningOperationState indicates an expected call of SetLongRunningOperationState.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) SetLongRunningOperationState(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLongRunningOperationState", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).SetLongRunningOperationState), arg0)
}

// ShouldReconcileKubeconfig mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) ShouldReconcileKubeconfig(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldReconcileKubeconfig", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldReconcileKubeconfig indicates an expected call of ShouldReconcileKubeconfig.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) ShouldReconcileKubeconfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldReconcileKubeconfig", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).ShouldReconcileKubeconfig), ctx)
}

// SubscriptionID mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) SubscriptionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriptionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SubscriptionID indicates an expected call of SubscriptionID.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) SubscriptionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriptionID", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).SubscriptionID))
}

// TenantID mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) TenantID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantID")
	ret0, _ := ret[0].(string)
	return ret0
}

// TenantID indicates an expected call of TenantID.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) TenantID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantID", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).TenantID))
}

// Token mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) Token() azcore.TokenCredential {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(azcore.TokenCredential)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).Token))
}

// UpdateDeleteStatus mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) UpdateDeleteStatus(arg0 v1beta10.ConditionType, arg1 string, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDeleteStatus", arg0, arg1, arg2)
}

// UpdateDeleteStatus indicates an expected call of UpdateDeleteStatus.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) UpdateDeleteStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeleteStatus", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).UpdateDeleteStatus), arg0, arg1, arg2)
}

// UpdatePatchStatus mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) UpdatePatchStatus(arg0 v1beta10.ConditionType, arg1 string, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePatchStatus", arg0, arg1, arg2)
}

// UpdatePatchStatus indicates an expected call of UpdatePatchStatus.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) UpdatePatchStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePatchStatus", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).UpdatePatchStatus), arg0, arg1, arg2)
}

// UpdatePutStatus mocks base method.
func (m *MockHcpOpenShiftClusterCredentialScope) UpdatePutStatus(arg0 v1beta10.ConditionType, arg1 string, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePutStatus", arg0, arg1, arg2)
}

// UpdatePutStatus indicates an expected call of UpdatePutStatus.
func (mr *MockHcpOpenShiftClusterCredentialScopeMockRecorder) UpdatePutStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePutStatus", reflect.TypeOf((*MockHcpOpenShiftClusterCredentialScope)(nil).UpdatePutStatus), arg0, arg1, arg2)
}
