apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: quay.io/capz/cluster-api-provider-azure-rhel9:v1.26.0-hcpclusters.1
        name: manager
